test:
  image: "docker.lanjing.cn/library/postgres:9.6-alpine"
  restart: always
  ports:
    - 10000:5432
  environment:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "123456"
  volumes:
    - ./data:/var/lib/postgresql/data
    - ./archive:/var/lib/postgresql/archive
    - ./init.sh:/docker-entrypoint-initdb.d/init.sh

