dns2:
  restart: always
  image: "mydns:7.0"
#  ports:
#    - 127.0.0.1:53:53
#    - 0.0.0.0:53:53
  volumes:
    - ./conf/named.conf:/etc/named.conf
    - ./conf/named.rfc1912.zones:/etc/named.rfc1912.zones
    - ./conf/my.com.zone:/var/named/my.com.zone


